name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux]

    steps:
      - name: Setup x11
        run: sudo apt-get install libx11-6:i386

      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.4.1
        with:
          name: bounce
          preset: ${{ matrix.platform }}
          debugMode: "true"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
